-- Seed data: Australian universities and common courses. Safe to re-run.
insert into public.universities (id, name, short_name, state) values
  ('UNSW', 'UNSW Sydney', 'UNSW', 'NSW'),
  ('USYD', 'University of Sydney', 'USYD', 'NSW'),
  ('UTS', 'University of Technology Sydney', 'UTS', 'NSW'),
  ('MQ', 'Macquarie University', 'Macquarie', 'NSW'),
  ('WSU', 'Western Sydney University', 'WSU', 'NSW'),
  ('UOW', 'University of Wollongong', 'UOW', 'NSW'),
  ('UON', 'University of Newcastle', 'Newcastle', 'NSW'),
  ('SCU', 'Southern Cross University', 'SCU', 'NSW'),
  ('CSU', 'Charles Sturt University', 'CSU', 'NSW'),
  ('UNE', 'University of New England', 'UNE', 'NSW'),
  ('ACU', 'Australian Catholic University', 'ACU', 'NSW'),
  ('UNIMELB', 'University of Melbourne', 'Melbourne', 'VIC'),
  ('MONASH', 'Monash University', 'Monash', 'VIC'),
  ('RMIT', 'RMIT University', 'RMIT', 'VIC'),
  ('DEAKIN', 'Deakin University', 'Deakin', 'VIC'),
  ('LATROBE', 'La Trobe University', 'La Trobe', 'VIC'),
  ('SWINBURNE', 'Swinburne University of Technology', 'Swinburne', 'VIC'),
  ('VU', 'Victoria University', 'VU', 'VIC'),
  ('FEDUNI', 'Federation University Australia', 'FedUni', 'VIC'),
  ('UQ', 'University of Queensland', 'UQ', 'QLD'),
  ('QUT', 'Queensland University of Technology', 'QUT', 'QLD'),
  ('GRIFFITH', 'Griffith University', 'Griffith', 'QLD'),
  ('JCU', 'James Cook University', 'JCU', 'QLD'),
  ('CQU', 'CQUniversity', 'CQU', 'QLD'),
  ('UNISQ', 'University of Southern Queensland', 'UniSQ', 'QLD'),
  ('USC', 'University of the Sunshine Coast', 'UniSC', 'QLD'),
  ('BOND', 'Bond University', 'Bond', 'QLD'),
  ('UWA', 'University of Western Australia', 'UWA', 'WA'),
  ('CURTIN', 'Curtin University', 'Curtin', 'WA'),
  ('MURDOCH', 'Murdoch University', 'Murdoch', 'WA'),
  ('ECU', 'Edith Cowan University', 'ECU', 'WA'),
  ('UNDA', 'University of Notre Dame Australia', 'Notre Dame', 'WA'),
  ('ADELAIDEU', 'Adelaide University', 'Adelaide Uni', 'SA'),
  ('FLINDERS', 'Flinders University', 'Flinders', 'SA'),
  ('UTAS', 'University of Tasmania', 'UTAS', 'TAS'),
  ('ANU', 'Australian National University', 'ANU', 'ACT'),
  ('UC', 'University of Canberra', 'UC', 'ACT'),
  ('CDU', 'Charles Darwin University', 'CDU', 'NT'),
  ('TORRENS', 'Torrens University Australia', 'Torrens', 'NSW'),
  ('AVONDALE', 'Avondale University', 'Avondale', 'NSW')
on conflict (id) do update set name = excluded.name, short_name = excluded.short_name, state = excluded.state;

insert into public.courses (uni_id, code, title, similar_group, source) values
  ('UNSW', 'COMP1511', 'Programming Fundamentals', 'prog', 'seed'),
  ('UNSW', 'COMP1521', 'Computer Systems Fundamentals', 'sys', 'seed'),
  ('UNSW', 'COMP1531', 'Software Engineering Fundamentals', 'se', 'seed'),
  ('UNSW', 'COMP2521', 'Data Structures and Algorithms', 'dsa', 'seed'),
  ('UNSW', 'COMP2511', 'Object-Oriented Design and Programming', 'oop', 'seed'),
  ('UNSW', 'COMP3311', 'Database Systems', 'db', 'seed'),
  ('UNSW', 'MATH1131', 'Mathematics 1A', 'calc', 'seed'),
  ('UNSW', 'MATH1231', 'Mathematics 1B', null, 'seed'),
  ('UNSW', 'MATH1081', 'Discrete Mathematics', 'discrete', 'seed'),
  ('UNSW', 'MATH1141', 'Higher Mathematics 1A', 'calc', 'seed'),
  ('UNSW', 'ECON1101', 'Microeconomics 1', 'micro', 'seed'),
  ('UNSW', 'ECON1102', 'Macroeconomics 1', 'macro', 'seed'),
  ('UNSW', 'ECON1203', 'Business and Economic Statistics', 'stats', 'seed'),
  ('UNSW', 'ACCT1501', 'Accounting and Financial Management 1A', 'acct', 'seed'),
  ('UNSW', 'ACCT1511', 'Accounting and Financial Management 1B', null, 'seed'),
  ('UNSW', 'FINS1612', 'Capital Markets and Institutions', null, 'seed'),
  ('UNSW', 'FINS1613', 'Business Finance', 'fin', 'seed'),
  ('UNSW', 'MGMT1001', 'Managing Organisations and People', 'mgmt', 'seed'),
  ('UNSW', 'MARK1012', 'Marketing Fundamentals', 'mkt', 'seed'),
  ('UNSW', 'INFS1602', 'Digital Transformation in Business', 'is', 'seed'),
  ('UNSW', 'INFS1603', 'Business Databases', 'db', 'seed'),
  ('UNSW', 'INFS1609', 'Fundamentals of Business Programming', 'oop', 'seed'),
  ('UNSW', 'INFS2603', 'Business Analysis', 'ba', 'seed'),
  ('UNSW', 'INFS2608', 'Database Management and Big Data Infrastructures', 'db', 'seed'),
  ('UNSW', 'INFS3604', 'Business Process Management', 'bpm', 'seed'),
  ('UNSW', 'COMM1100', 'Business Decision Making', null, 'seed'),
  ('UNSW', 'COMM1140', 'Financial Management', null, 'seed'),
  ('UNSW', 'COMM1170', 'Organisational Resources', null, 'seed'),
  ('UNSW', 'COMM1180', 'Value Creation', null, 'seed'),
  ('UNSW', 'COMM1190', 'Data, Insights and Decisions', null, 'seed'),
  ('UNSW', 'ENGG1811', 'Computing for Engineers', 'prog', 'seed'),
  ('UNSW', 'PHYS1121', 'Physics 1A', 'phys', 'seed'),
  ('UNSW', 'CHEM1011', 'Chemistry A', 'chem', 'seed'),
  ('UNSW', 'PSYC1001', 'Psychology 1A', 'psych', 'seed'),
  ('UNSW', 'LAWS1052', 'Introducing Law and Justice', 'law', 'seed'),
  ('USYD', 'INFO1110', 'Introduction to Programming', 'prog', 'seed'),
  ('USYD', 'INFO1111', 'Computing 1A Professionalism', null, 'seed'),
  ('USYD', 'INFO1112', 'Computing 1B OS and Network Platforms', 'sys', 'seed'),
  ('USYD', 'INFO1113', 'Object-Oriented Programming', 'oop', 'seed'),
  ('USYD', 'COMP2123', 'Data Structures and Algorithms', 'dsa', 'seed'),
  ('USYD', 'COMP2017', 'Systems Programming', null, 'seed'),
  ('USYD', 'INFO2222', 'Computing 2 Usability and Security', null, 'seed'),
  ('USYD', 'DATA1001', 'Foundations of Data Science', null, 'seed'),
  ('USYD', 'MATH1021', 'Calculus of One Variable', 'calc', 'seed'),
  ('USYD', 'MATH1002', 'Linear Algebra', 'linalg', 'seed'),
  ('USYD', 'MATH1023', 'Multivariable Calculus and Modelling', null, 'seed'),
  ('USYD', 'ECON1001', 'Introductory Microeconomics', 'micro', 'seed'),
  ('USYD', 'ECON1002', 'Introductory Macroeconomics', 'macro', 'seed'),
  ('USYD', 'BUSS1020', 'Quantitative Business Analysis', 'stats', 'seed'),
  ('USYD', 'ACCT1006', 'Accounting and Financial Management', 'acct', 'seed'),
  ('USYD', 'BUSS1030', 'Accounting, Business and Society', null, 'seed'),
  ('USYD', 'FINC2011', 'Corporate Finance I', 'fin', 'seed'),
  ('USYD', 'PSYC1001', 'Psychology 1001', 'psych', 'seed'),
  ('UTS', '48023', 'Programming Fundamentals', 'prog', 'seed'),
  ('UTS', '48024', 'Applications Programming', 'oop', 'seed'),
  ('UTS', '31268', 'Web Systems', 'web', 'seed'),
  ('UTS', '31271', 'Database Fundamentals', 'db', 'seed'),
  ('UTS', '31251', 'Data Structures and Algorithms', 'dsa', 'seed'),
  ('UTS', '33130', 'Mathematical Modelling 1', 'calc', 'seed'),
  ('UTS', '22107', 'Accounting for Business Decisions A', 'acct', 'seed'),
  ('UTS', '23115', 'Economics for Business', 'micro', 'seed'),
  ('UTS', '25300', 'Fundamentals of Business Finance', 'fin', 'seed'),
  ('UTS', '24108', 'Marketing Foundations', 'mkt', 'seed'),
  ('MQ', 'COMP1000', 'Introduction to Computer Programming', 'prog', 'seed'),
  ('MQ', 'COMP1010', 'Fundamentals of Computer Science', 'dsa', 'seed'),
  ('MQ', 'COMP1350', 'Introduction to Database Design and Management', 'db', 'seed'),
  ('MQ', 'STAT1170', 'Introductory Statistics', 'stats', 'seed'),
  ('MQ', 'ACCG1000', 'Accounting for Decision Making', 'acct', 'seed'),
  ('MQ', 'MATH1010', 'Calculus and Linear Algebra I', 'calc', 'seed'),
  ('MQ', 'PSYU1101', 'Psychology: Human Behaviour', 'psych', 'seed'),
  ('WSU', '300580', 'Programming Fundamentals', 'prog', 'seed'),
  ('WSU', '300581', 'Programming Techniques', 'oop', 'seed'),
  ('WSU', '300582', 'Technologies for Web Applications', 'web', 'seed'),
  ('WSU', '300585', 'Systems Analysis and Design', 'ba', 'seed'),
  ('WSU', '300103', 'Data Structures and Algorithms', 'dsa', 'seed'),
  ('UOW', 'CSIT111', 'Programming Fundamentals', 'prog', 'seed'),
  ('UOW', 'CSIT113', 'Problem Solving', null, 'seed'),
  ('UOW', 'CSIT114', 'System Analysis', 'ba', 'seed'),
  ('UOW', 'CSIT115', 'Data Management and Security', 'db', 'seed'),
  ('UOW', 'CSCI203', 'Algorithms and Data Structures', 'dsa', 'seed'),
  ('UON', 'SENG1110', 'Object Oriented Programming', 'oop', 'seed'),
  ('UON', 'SENG1120', 'Data Structures', 'dsa', 'seed'),
  ('UON', 'INFT2040', 'Database Management Systems', 'db', 'seed'),
  ('UON', 'MATH1110', 'Mathematics 1', 'calc', 'seed'),
  ('UON', 'STAT1070', 'Statistics for the Sciences', 'stats', 'seed'),
  ('UNIMELB', 'COMP10001', 'Foundations of Computing', 'prog', 'seed'),
  ('UNIMELB', 'COMP10002', 'Foundations of Algorithms', 'dsa', 'seed'),
  ('UNIMELB', 'COMP20003', 'Algorithms and Data Structures', 'dsa', 'seed'),
  ('UNIMELB', 'COMP20008', 'Elements of Data Processing', null, 'seed'),
  ('UNIMELB', 'INFO20003', 'Database Systems', 'db', 'seed'),
  ('UNIMELB', 'MAST10005', 'Calculus 1', 'calc', 'seed'),
  ('UNIMELB', 'MAST10006', 'Calculus 2', null, 'seed'),
  ('UNIMELB', 'MAST10007', 'Linear Algebra', 'linalg', 'seed'),
  ('UNIMELB', 'ECON10004', 'Introductory Microeconomics', 'micro', 'seed'),
  ('UNIMELB', 'ECON10003', 'Introductory Macroeconomics', 'macro', 'seed'),
  ('UNIMELB', 'ACCT10001', 'Accounting Reports and Analysis', 'acct', 'seed'),
  ('UNIMELB', 'ACCT10002', 'Introductory Financial Accounting', null, 'seed'),
  ('UNIMELB', 'FNCE10002', 'Principles of Finance', 'fin', 'seed'),
  ('UNIMELB', 'MKTG10001', 'Principles of Marketing', 'mkt', 'seed'),
  ('UNIMELB', 'PSYC10003', 'Mind, Brain and Behaviour 1', 'psych', 'seed'),
  ('MONASH', 'FIT1045', 'Introduction to Programming', 'prog', 'seed'),
  ('MONASH', 'FIT1051', 'Programming Fundamentals in Java', 'oop', 'seed'),
  ('MONASH', 'FIT1008', 'Fundamentals of Algorithms', 'dsa', 'seed'),
  ('MONASH', 'FIT2004', 'Algorithms and Data Structures', 'dsa', 'seed'),
  ('MONASH', 'FIT2094', 'Databases', 'db', 'seed'),
  ('MONASH', 'FIT1047', 'Introduction to Computer Systems, Networks and Security', 'sys', 'seed'),
  ('MONASH', 'MTH1030', 'Techniques for Modelling', 'calc', 'seed'),
  ('MONASH', 'MTH1020', 'Analysis of Change', null, 'seed'),
  ('MONASH', 'ETC1000', 'Business and Economic Statistics', 'stats', 'seed'),
  ('MONASH', 'ECC1000', 'Principles of Microeconomics', 'micro', 'seed'),
  ('MONASH', 'ECC1100', 'Principles of Macroeconomics', 'macro', 'seed'),
  ('MONASH', 'ACC1100', 'Introduction to Financial Accounting', 'acct', 'seed'),
  ('MONASH', 'AFF1000', 'Principles of Accounting and Finance', null, 'seed'),
  ('MONASH', 'BFF1001', 'Foundations of Finance', 'fin', 'seed'),
  ('MONASH', 'MKF1120', 'Marketing Theory and Practice', 'mkt', 'seed'),
  ('MONASH', 'PSY1011', 'Psychology 1A', 'psych', 'seed'),
  ('RMIT', 'COSC2531', 'Programming Fundamentals', 'prog', 'seed'),
  ('RMIT', 'COSC1076', 'Advanced Programming Techniques', 'oop', 'seed'),
  ('RMIT', 'ISYS1057', 'Database Concepts', 'db', 'seed'),
  ('DEAKIN', 'SIT102', 'Introduction to Programming', 'prog', 'seed'),
  ('DEAKIN', 'SIT111', 'Computer Systems', 'sys', 'seed'),
  ('DEAKIN', 'SIT103', 'Database Fundamentals', 'db', 'seed'),
  ('DEAKIN', 'SIT221', 'Data Structures and Algorithms', 'dsa', 'seed'),
  ('LATROBE', 'CSE1OOF', 'Object-Oriented Programming Fundamentals', 'prog', 'seed'),
  ('LATROBE', 'CSE1IOO', 'Intermediate Object-Oriented Programming', 'oop', 'seed'),
  ('LATROBE', 'CSE2DBF', 'Database Fundamentals', 'db', 'seed'),
  ('SWINBURNE', 'COS10009', 'Introduction to Programming', 'prog', 'seed'),
  ('SWINBURNE', 'COS20007', 'Object Oriented Programming', 'oop', 'seed'),
  ('UQ', 'CSSE1001', 'Introduction to Software Engineering', 'prog', 'seed'),
  ('UQ', 'CSSE2002', 'Programming in the Large', 'oop', 'seed'),
  ('UQ', 'CSSE2010', 'Introduction to Computer Systems', 'sys', 'seed'),
  ('UQ', 'COMP3506', 'Algorithms and Data Structures', 'dsa', 'seed'),
  ('UQ', 'INFS1200', 'Introduction to Information Systems', 'is', 'seed'),
  ('UQ', 'DECO1400', 'Introduction to Web Design', 'web', 'seed'),
  ('UQ', 'MATH1051', 'Calculus and Linear Algebra I', 'calc', 'seed'),
  ('UQ', 'STAT1201', 'Analysis of Scientific Data', null, 'seed'),
  ('UQ', 'ECON1010', 'Introductory Microeconomics', 'micro', 'seed'),
  ('UQ', 'ECON1020', 'Introductory Macroeconomics', 'macro', 'seed'),
  ('UQ', 'ECON1310', 'Introductory Statistics for Social Sciences', 'stats', 'seed'),
  ('UQ', 'ACCT1101', 'Accounting for Decision Making', 'acct', 'seed'),
  ('QUT', 'CAB201', 'Programming Principles', 'prog', 'seed'),
  ('QUT', 'IFB104', 'Building IT Systems', null, 'seed'),
  ('QUT', 'IFB103', 'IT Systems Design', 'ba', 'seed'),
  ('QUT', 'IFB105', 'Database Management', 'db', 'seed'),
  ('QUT', 'CAB230', 'Web Computing', 'web', 'seed'),
  ('QUT', 'CAB202', 'Microprocessors and Digital Systems', 'sys', 'seed'),
  ('QUT', 'BSB110', 'Accounting', 'acct', 'seed'),
  ('QUT', 'BSB113', 'Economics', 'micro', 'seed'),
  ('QUT', 'BSB123', 'Data Analysis', 'stats', 'seed'),
  ('QUT', 'BSB126', 'Marketing', 'mkt', 'seed'),
  ('JCU', 'CP1401', 'Fundamentals of Problem Solving and Programming I', 'prog', 'seed'),
  ('JCU', 'CP1404', 'Programming II', 'oop', 'seed'),
  ('UWA', 'CITS1401', 'Computational Thinking with Python', 'prog', 'seed'),
  ('UWA', 'CITS1402', 'Relational Database Management Systems', 'db', 'seed'),
  ('UWA', 'CITS2200', 'Data Structures and Algorithms', 'dsa', 'seed'),
  ('UWA', 'MATH1011', 'Multivariable Calculus', null, 'seed'),
  ('UWA', 'MATH1012', 'Mathematical Theory and Methods', null, 'seed'),
  ('UWA', 'ECON1101', 'Microeconomics: Prices and Markets', 'micro', 'seed'),
  ('UWA', 'ECON1102', 'Macroeconomics: Money and Finance', 'macro', 'seed'),
  ('UWA', 'ACCT1101', 'Financial Accounting', 'acct', 'seed'),
  ('UWA', 'STAT1400', 'Statistics for Science', 'stats', 'seed'),
  ('CURTIN', 'COMP1005', 'Fundamentals of Programming', 'prog', 'seed'),
  ('CURTIN', 'COMP1007', 'Unix and C Programming', 'sys', 'seed'),
  ('CURTIN', 'ISYS1001', 'Database Systems', 'db', 'seed'),
  ('FLINDERS', 'COMP1102', 'Computer Programming 1', 'prog', 'seed'),
  ('UTAS', 'KIT101', 'Programming Fundamentals', 'prog', 'seed'),
  ('UTAS', 'KIT205', 'Data Structures and Algorithms', 'dsa', 'seed'),
  ('ANU', 'COMP1100', 'Programming as Problem Solving', 'prog', 'seed'),
  ('ANU', 'COMP1730', 'Programming for Scientists', 'prog', 'seed'),
  ('ANU', 'COMP1110', 'Structured Programming', 'oop', 'seed'),
  ('ANU', 'COMP2100', 'Software Design Methodologies', 'se', 'seed'),
  ('ANU', 'COMP2400', 'Relational Databases', 'db', 'seed'),
  ('ANU', 'MATH1013', 'Mathematics and Applications 1', 'calc', 'seed'),
  ('ANU', 'MATH1014', 'Mathematics and Applications 2', 'linalg', 'seed'),
  ('ANU', 'ECON1101', 'Microeconomics 1', 'micro', 'seed'),
  ('ANU', 'ECON1102', 'Macroeconomics 1', 'macro', 'seed'),
  ('ANU', 'STAT1003', 'Statistical Techniques', 'stats', 'seed'),
  ('ANU', 'BUSN1001', 'Business Reporting and Analysis', 'acct', 'seed'),
  ('ANU', 'FINM1001', 'Foundations of Finance', 'fin', 'seed')
on conflict (uni_id, code) do update set title = excluded.title, similar_group = excluded.similar_group;
