// Supabase Edge Function: check-answer
// Scores how likely a tutor's answer was written by AI (0 to 100) with Claude, combined with how much of it
// was typed by hand. Answers over 40% are flagged and the tutor gets a warning.
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.45.4";

const MODEL = "claude-haiku-4-5-20251001";
const THRESHOLD = 40;
const cors = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};
const json = (b: unknown, s = 200) => new Response(JSON.stringify(b), { status: s, headers: { ...cors, "Content-Type": "application/json" } });

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: cors });
  const apiKey = Deno.env.get("ANTHROPIC_API_KEY");
  if (!apiKey) return json({ error: "Checks aren't set up." }, 503);

  const userClient = createClient(Deno.env.get("SUPABASE_URL")!, Deno.env.get("SUPABASE_ANON_KEY")!, {
    global: { headers: { Authorization: req.headers.get("Authorization") ?? "" } },
  });
  const { data: { user } } = await userClient.auth.getUser();
  if (!user) return json({ error: "Sign in first." }, 401);

  let answer_id = "", typed = 0, total = 0;
  try { ({ answer_id, typed, total } = await req.json()); } catch { /* checked below */ }
  const admin = createClient(Deno.env.get("SUPABASE_URL")!, Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!);

  const { data: a } = await admin.from("answers").select("id, tutor_id, question_id, bubbles, created_at").eq("id", answer_id).maybeSingle();
  if (!a || a.tutor_id !== user.id) return json({ error: "Answer not found" }, 404);
  const { data: existing } = await admin.from("answer_checks").select("ai_score, flagged").eq("answer_id", a.id).maybeSingle();
  if (existing) return json(existing);
  const { data: q } = await admin.from("questions").select("course_code, body").eq("id", a.question_id).maybeSingle();

  const answer = (a.bubbles ?? []).join("\n\n");
  const prompt = `You check answers on a peer tutoring site. University students ask short questions, and other students (tutors) must answer in their own words, typed by hand in about 2 minutes. Answers written by ChatGPT, Claude or other AI tools are not allowed.

Estimate the likelihood, from 0 to 100, that the ANSWER below was generated by an AI tool rather than typed by a student.
Signs of AI: polished, generic or textbook phrasing; tidy structure with headings, numbered steps or bullet points; markdown (** or ##); phrases like "Great question", "Certainly", "In summary", "It's important to note"; em dashes; perfectly consistent grammar at length; covering every angle instead of the student's specific problem.
Signs of a human: casual tone, abbreviations, small typos, uneven sentences, referring directly to the student's situation, brevity.
Short, casual answers are usually human. Don't penalise good English on its own, or answers from people writing in a second language.

Reply with ONLY JSON: {"score": 0-100, "reason": "one short sentence"}

<question course="${q?.course_code ?? ""}">${q?.body ?? ""}</question>
<answer>
${answer}
</answer>`;

  let score = 0, reason = "";
  const res = await fetch("https://api.anthropic.com/v1/messages", {
    method: "POST",
    headers: { "x-api-key": apiKey, "anthropic-version": "2023-06-01", "content-type": "application/json" },
    body: JSON.stringify({ model: MODEL, max_tokens: 200, messages: [{ role: "user", content: prompt }] }),
  });
  if (res.ok) {
    const out = await res.json();
    const text: string = (out.content ?? []).filter((c: { type: string }) => c.type === "text").map((c: { text: string }) => c.text).join("");
    try {
      const p = JSON.parse(text.slice(text.indexOf("{"), text.lastIndexOf("}") + 1));
      score = Math.max(0, Math.min(100, Math.round(Number(p.score) || 0)));
      reason = String(p.reason ?? "").slice(0, 300);
    } catch { /* leave 0 */ }
  } else console.error("Anthropic", res.status, await res.text());

  // Typing check: characters that arrived without keystrokes (autofill, extensions, dictation tools)
  const len = answer.replace(/\s/g, "").length;
  const ratio = total > 0 ? Math.max(0, Math.min(1, Number(typed) / Number(total))) : null;
  if (ratio !== null && len > 40 && ratio < 0.6) {
    score = Math.max(score, 80);
    reason = `Only ${Math.round(ratio * 100)}% of the answer was typed on the keyboard. ` + reason;
  }

  const flagged = score > THRESHOLD;
  await admin.from("answer_checks").insert({ answer_id: a.id, tutor_id: user.id, ai_score: score, typed_ratio: ratio, flagged, reason });
  if (flagged) {
    const { data: p } = await admin.from("profiles").select("ai_flags").eq("id", user.id).single();
    await admin.from("profiles").update({ ai_flags: (p?.ai_flags ?? 0) + 1 }).eq("id", user.id);
  }
  return json({ ai_score: score, flagged });
});
